# Семинар 3: Векторы слов

Другие курсы на ту же тему:
* https://github.com/DanAnastasyev/DeepNLP-Course: Курс Данила Анастасьева, Week 2
* https://www.youtube.com/watch?v=ERibwqs9p38: Stanford CS224n, Lecture 2
* https://github.com/deepmipt/deep-nlp-seminars: Курс DeepMIPT, Seminar 2

In [ ]:
!apt-get update
!apt-get install -y python-setuptools python-pip
!pip install --upgrade pybind11 setuptools

Get:1 https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease [3,622 B]
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease
Get:3 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal InRelease [18.1 kB]
Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease
Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Hit:7 http://ppa.launchpad.net/cran/libgit2/ubuntu focal InRelease
Get:8 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:9 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2,545 kB]
Get:10 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [3,026 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [28.6 kB]
Hit:12 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease
Hit:13 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal

In [ ]:
%%writefile requirements.txt
gensim==3.8.3
pandas
razdel
hnswlib

Writing requirements.txt


In [ ]:
!pip install --upgrade -r requirements.txt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.4/23.4 MB 58.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 26.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for gensim: filename=gensim-3.8.3-cp39-cp39-linux_x86_64.whl size=26528082 sha256=def48103082c282aa640bf29cd032ad6d8f9024c74c225250f11853d5b76c646
  Stored in directory: /root/.cache/pip/wheels/ca/5d/af/618594ec2f28608c1d6ee7d2b7e95a3e9b06551e3b80a491d6
  Created wheel for hnswlib: filename=hnswlib-0.7.0-cp39-cp39-linux_x86_64.whl size=2118301 sha256=bed5f37c0c1d39dbd917daa11144d26fc1050c3ae2244048104085df3920ab0f
  Stored in directory: /root/.cache/pip/wheels/ba/26/61/fface6c407f56418b3140cd7645917f20ba6b27d4e32b2bd20
Successfully built gen

### Скачиваем датасет на сегодня

In [ ]:
!wget https://github.com/yutkin/Lenta.Ru-News-Dataset/releases/download/v1.0/lenta-ru-news.csv.gz
!gzip -d lenta-ru-news.csv.gz
!head -n 2 lenta-ru-news.csv

--2023-03-22 19:36:41--  https://github.com/yutkin/Lenta.Ru-News-Dataset/releases/download/v1.0/lenta-ru-news.csv.gz
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/87156914/0b363e00-0126-11e9-9e3c-e8c235463bd6?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20230322%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230322T193641Z&X-Amz-Expires=300&X-Amz-Signature=ba1ecea4f2304c63b9c7c3b11b054c1bbbd464d10c27885dc1855cba18511817&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=87156914&response-content-disposition=attachment%3B%20filename%3Dlenta-ru-news.csv.gz&response-content-type=application%2Foctet-stream [following]
--2023-03-22 19:36:42--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/87156914/0b363e00-0126-11e9-9e3c-e8

### Обрабатываем датасет

In [ ]:
import pandas as pd

dataset = pd.read_csv("lenta-ru-news.csv", sep=',', quotechar='\"', escapechar='\\', encoding='utf-8', header=0)
dataset.head()

url  \
0      https://lenta.ru/news/2018/12/14/cancer/   
1      https://lenta.ru/news/2018/12/15/doping/   
2  https://lenta.ru/news/2018/12/15/disneyland/   
3       https://lenta.ru/news/2018/12/15/usa25/   
4   https://lenta.ru/news/2018/12/15/integrity/   

                                               title  \
0  Названы регионы России с самой высокой смертно...   
1  Австрия не представила доказательств вины росс...   
2       Обнаружено самое счастливое место на планете   
3  В США раскрыли сумму расходов на расследование...   
4  Хакеры рассказали о планах Великобритании зами...   

                                                text        topic         tags  
0  Вице-премьер по социальным вопросам Татьяна Го...       Россия     Общество  
1  Австрийские правоохранительные органы не предс...        Спорт  Зимние виды  
2  Сотрудники социальной сети Instagram проанализ...  Путешествия          Мир  
3  С начала расследования российского вмешательст...          Мир     Политика  
4  Хакерская группировка Anonymous опубликовала н...          Мир     Общество

In [ ]:
import re
import datetime as dt

def get_date(url):
    dates = re.findall(r"\d\d\d\d\/\d\d\/\d\d", url)
    return next(iter(dates), None)
  
dataset["date"] = dataset["url"].apply(lambda x: dt.datetime.strptime(get_date(x), "%Y/%m/%d"))
dataset = dataset[dataset["date"] > "2017-01-01"]
dataset["text"] = dataset["text"].apply(lambda x: x.replace("\xa0", " "))
dataset["title"] = dataset["title"].apply(lambda x: x.replace("\xa0", " "))
dataset.head()

<ipython-input-6-75cf894f2c6e>:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["text"] = dataset["text"].apply(lambda x: x.replace("\xa0", " "))
<ipython-input-6-75cf894f2c6e>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["title"] = dataset["title"].apply(lambda x: x.replace("\xa0", " "))


url  \
0      https://lenta.ru/news/2018/12/14/cancer/   
1      https://lenta.ru/news/2018/12/15/doping/   
2  https://lenta.ru/news/2018/12/15/disneyland/   
3       https://lenta.ru/news/2018/12/15/usa25/   
4   https://lenta.ru/news/2018/12/15/integrity/   

                                               title  \
0  Названы регионы России с самой высокой смертно...   
1  Австрия не представила доказательств вины росс...   
2       Обнаружено самое счастливое место на планете   
3  В США раскрыли сумму расходов на расследование...   
4  Хакеры рассказали о планах Великобритании зами...   

                                                text        topic  \
0  Вице-премьер по социальным вопросам Татьяна Го...       Россия   
1  Австрийские правоохранительные органы не предс...        Спорт   
2  Сотрудники социальной сети Instagram проанализ...  Путешествия   
3  С начала расследования российского вмешательст...          Мир   
4  Хакерская группировка Anonymous опубликовала н...          Мир   

          tags       date  
0     Общество 2018-12-14  
1  Зимние виды 2018-12-15  
2          Мир 2018-12-15  
3     Политика 2018-12-15  
4     Общество 2018-12-15

In [ ]:
train_dataset = dataset[dataset["date"] < "2018-04-01"]
test_dataset = dataset[dataset["date"] > "2018-04-01"]
print(train_dataset.info())
print(test_dataset.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 69285 entries, 31339 to 701898
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   url     69285 non-null  object        
 1   title   69285 non-null  object        
 2   text    69285 non-null  object        
 3   topic   69277 non-null  object        
 4   tags    65739 non-null  object        
 5   date    69285 non-null  datetime64[ns]
dtypes: datetime64[ns](1), object(5)
memory usage: 3.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 31289 entries, 0 to 31289
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   url     31289 non-null  object        
 1   title   31289 non-null  object        
 2   text    31289 non-null  object        
 3   topic   31280 non-null  object        
 4   tags    30986 non-null  object        
 5   date    31289 non-null  datetime64[ns]
dtypes: dat

# Задачи, которые будем решать
* Семантический поиск по заголовку
* Рубрикация

## Подготовка: разбиение на предложения и токенизация

In [ ]:
from razdel import tokenize, sentenize
from string import punctuation
from tqdm import tqdm

texts = []
for text in tqdm(train_dataset["text"]):
    # Разбейте на предложения
    # Каждое предложение токенизируйте и список токенов положите в texts.
    # Токены приведите к нижнему регистру и избавьтесь от пунктуации.
    for sent in sentenize(text):
      text_i = [ j.text.lower() for j in tokenize(sent.text) if j.text not in list(punctuation)]
      texts.append(text_i)
    
for title in tqdm(train_dataset["title"]):
    # Считайте заголовок одним предложением
    text_i = [j.text.lower() for j in tokenize(text) if j.text not in list(punctuation)]
    texts.append(text_i)

assert len(texts) == 827217
assert len(texts[0]) > 0
assert texts[0][0].islower()
print(texts[0])

100%|██████████| 69285/69285 [01:55<00:00, 597.39it/s]

['возобновление', 'нормального', 'сотрудничества', 'между', 'россией', 'и', 'нато', 'невозможно', 'пока', 'москва', 'не', 'будет', 'соблюдать', 'нормы', 'международного', 'права']


## Коротко о Word2Vec
Обучение:

![embeddings training](https://miro.medium.com/max/1400/0*o2FCVrLKtdcxPQqc.png)
*From [An implementation guide to Word2Vec using NumPy and Google Sheets
](https://towardsdatascience.com/an-implementation-guide-to-word2vec-using-numpy-and-google-sheets-13445eebd281)*

![embeddings relations](https://www.tensorflow.org/images/linear-relationships.png)
*From [Vector Representations of Words, Tensorflow tutorial](https://www.tensorflow.org/tutorials/representation/word2vec)*

Статьи:
* Word2Vec: [Distributed Representations of Words and Phrases
and their Compositionality](https://papers.nips.cc/paper/5021-distributed-representations-of-words-and-phrases-and-their-compositionality.pdf), Mikolov et al., 2013
* GloVe: [GloVe: Global Vectors for Word Representation](https://nlp.stanford.edu/pubs/glove.pdf), Pennington, Socher, Manning, 2014
* fastText: [Enriching Word Vectors with Subword Information](https://arxiv.org/pdf/1607.04606.pdf), Bojanowski, Grave, Joulin, Mikolov, 2016

Ссылки:
* Word2Vec и fasttext модели для русского: https://rusvectores.org/ru/
* fasttext для кучи языков: https://fasttext.cc/
* Ещё fasttext модели для русского: http://docs.deeppavlov.ai/en/master/features/pretrained_vectors.html
* Отдельная библиотека для русских векторов: https://github.com/natasha/navec
* Word2Vec для кучи языков, обученная на Вики: https://wikipedia2vec.github.io/wikipedia2vec/pretrained/
* Word2Vec для английского от Гугла: https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM
* Огромная Word2Vec модель для русского: https://zenodo.org/record/400631#.Xa4RPN9fjCI

## Тренируем простую модель

In [ ]:
from gensim.models import Word2Vec

model = Word2Vec(texts, 
                 size=32, # embedding vector size
                 min_count=5,    # consider words that occured at least 5 times
                 window=5).wv    # define context as a 5-word window around the target word

Полноценная тренировка в следующий раз :)
А теперь немного потестируем нашу модель.

## Тестируем модель

In [ ]:
model.get_vector("сша")

array([ 0.30915418, -2.8537261 , -0.56802493,  5.758164  , -2.5617576 ,
        2.29948   , -2.2163815 ,  8.68865   ,  0.43382534,  1.5854142 ,
       -2.6772332 , -3.890408  ,  2.293331  ,  2.0646412 , -2.5083125 ,
       -1.5825833 ,  2.3530288 ,  8.033071  ,  6.514632  , -1.3326265 ,
       -0.7735151 , -1.3837216 , -0.18940035, -0.9481554 , -3.2902863 ,
        2.2421956 ,  0.03512082,  2.2246578 ,  1.8303664 ,  0.8511859 ,
        2.6453295 , -3.0836704 ], dtype=float32)

In [ ]:
model.most_similar('сша')

[('великобритании', 0.888203501701355),
 ('турции', 0.8577114939689636),
 ('кндр', 0.8488249778747559),
 ('страны', 0.8290386199951172),
 ('соединенных', 0.813773512840271),
 ('кнр', 0.811214804649353),
 ('японии', 0.8077250123023987),
 ('польши', 0.7930467128753662),
 ('королевства', 0.7914412021636963),
 ('германии', 0.7901788949966431)]

In [ ]:
model.most_similar([model.get_vector('трамп') - model.get_vector('сша') + model.get_vector('россии')])

[('путин', 0.7190757393836975),
 ('россии', 0.7155882120132446),
 ('медведев', 0.7089120149612427),
 ('он', 0.6961963176727295),
 ('трамп', 0.6928441524505615),
 ('порошенко', 0.6823128461837769),
 ('жириновский', 0.6811381578445435),
 ('лукашенко', 0.6575406789779663),
 ('россия', 0.655292809009552),
 ('политик', 0.6496386528015137)]

### Задание: Найдите свою аналогию
Поиграйтесь с моделью и найдите свои аналогии. Можно здесь, можно на rusvectores



In [ ]:
model.similarity('мотоцикл', 'скорость')

0.39315593

In [ ]:
model.similarity('преподаватель', 'ученик')

0.8017324

In [ ]:
 model.similarity('тренер', 'спортсмен')

0.65965855

## Визуализируем векторы

In [ ]:
import bokeh.models as bm, bokeh.plotting as pl
from bokeh.io import output_notebook

def draw_vectors(x, y, radius=10, alpha=0.25, color='blue',
                 width=600, height=400, show=True, **kwargs):
    output_notebook()
    
    if isinstance(color, str): 
        color = [color] * len(x)
    data_source = bm.ColumnDataSource({'x' : x, 'y' : y, 'color': color, **kwargs})

    fig = pl.figure(active_scroll='wheel_zoom', width=width, height=height)
    fig.scatter('x', 'y', size=radius, color='color', alpha=alpha, source=data_source)

    fig.add_tools(bm.HoverTool(tooltips=[(key, "@" + key) for key in kwargs.keys()]))
    if show:
        pl.show(fig)
    return fig

In [ ]:
words = sorted(model.vocab.keys(), 
               key=lambda word: model.vocab[word].count,
               reverse=True)[:1000]
word_vectors = model.vectors[[model.vocab[word].index for word in words]]

### PCA

Простейший линейный метод сокращения размерностей - __P__rincipial __C__omponent __A__nalysis.

PCA ищет оси, при проекции на которые данные будут иметь наибольший разброс.

![pca](https://i.stack.imgur.com/Q7HIP.gif)
*From [https://stats.stackexchange.com/a/140579](https://stats.stackexchange.com/a/140579)*

В результате, можно взять проекции на несколько первых компонент - и сохранить как можно больше информации, сократив размерность.

Красивые визуализации можно найти [здесь](http://setosa.io/ev/principal-component-analysis/).

In [ ]:
from sklearn.decomposition import PCA
pca_model = PCA(n_components=2)
pca_vectors = pca_model.fit_transform(word_vectors)
pca_vectors = (pca_vectors - pca_vectors.mean(0)) / pca_vectors.std(0)

In [ ]:
draw_vectors(pca_vectors[:, 0], pca_vectors[:, 1], token=words)

Figure(id='1003', ...)

Получилось не очень понятно.

### TSNE

Более интересный и сложный (нелинейный) метод для визуализации высокоразмерных пространств - TSNE. Подробно посмотреть на него можно [здесь](https://distill.pub/2016/misread-tsne/) (ещё более красивые картинки!).

### Задание: TSNE
Сделайте то же самое, но с TSNE

In [ ]:
# CODE HERE
from sklearn.manifold import TSNE

tsne_model = TSNE(n_components=2)
tsne_vectors = tsne_model.fit_transform(word_vectors)
tsne_vectors = (tsne_vectors - tsne_vectors.mean(0)) / tsne_vectors.std(0)

In [ ]:
draw_vectors(tsne_vectors[:, 0], tsne_vectors[:, 1], token=words)

Figure(id='1113', ...)

## Поиск заголовков

In [ ]:
from razdel import tokenize
import numpy as np

def get_text_embedding(model, phrase):
    embeddings = np.array([model.get_vector(word.text.lower()) if word.text.lower() in model.vocab else np.zeros((model.vector_size,))
                           for word in tokenize(phrase)])
    return np.mean(embeddings, axis=0)
    
get_text_embedding(model, "В Москве нашли")

array([ 1.321117  , -1.0921036 , -1.1095904 ,  0.63538224, -0.15392686,
        0.9900057 , -4.057417  , -1.4839578 , -0.71346134,  2.2411342 ,
        0.16207345, -2.0046031 , -0.67202735,  3.1639767 ,  1.9503669 ,
        1.2530228 , -1.6571292 ,  2.2375321 ,  2.4072728 ,  0.40195227,
        0.56932366,  1.0859137 , -0.23089452,  1.163849  ,  2.0034819 ,
        2.2305267 , -3.3401434 ,  0.45663118, -2.2072046 , -2.594073  ,
        1.7829605 ,  0.51894456], dtype=float32)

### Задание: k ближайших заголовков
Напишите функцию для поиска похожих на запрос заголовков


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

def find_nearest(model, text_vectors, texts, query, k=10):
    # YOUR CODE HERE
    query_vector = get_text_embedding(model, query)
    cos_list = [cosine_similarity( query_vector.reshape(1,-1), i.reshape(1,-1)) for i in title_vectors]
    k_nearest_titles = [texts[cos_list.index(i)] for i in sorted(cos_list, reverse=True)[:k]]
    return k_nearest_titles

test_titles = test_dataset["title"].tolist()
title_vectors = np.array([get_text_embedding(model, title) for title in test_titles])

In [ ]:
query = "В Москве нашли"
near_titles = find_nearest(model, title_vectors, test_titles, query)
assert len(near_titles) == 10

near_titles

['Дом-хамелеон обнаружили в Москве',
 'В Москве обнаружили засилье несуществующих ЖК',
 'В Подмосковье нашли похороненную заживо овчарку',
 'В Подмосковье нашли редкое водное растение',
 'В Москве ликвидировали подпольный игорный синдикат',
 'В Москве госпитализировали певицу Лободу',
 'Безработный обманом завладел квартирой пенсионерки в Москве',
 'В Подмосковье обнаружили редкую хищную птицу',
 'Арестованных украинских моряков нашли в Москве',
 'Неизвестное ядовитое вещество применили в Лондоне']

### HNSW-индекс

Поиск за log(n)

* https://github.com/nmslib/hnswlib
* https://habr.com/ru/company/mailru/blog/338360/
* https://arxiv.org/ftp/arxiv/papers/1603/1603.09320.pdf

In [ ]:
import hnswlib

hnsw = hnswlib.Index(space='cosine', dim=title_vectors.shape[1])
hnsw.init_index(max_elements=title_vectors.shape[0])
hnsw.add_items(title_vectors)

In [ ]:
labels, distances = hnsw.knn_query(get_text_embedding(model, query), k=3)
near_titles = [test_titles[i] for i in labels[0]]
near_titles

['Дом-хамелеон обнаружили в Москве',
 'В Москве обнаружили засилье несуществующих ЖК',
 'В Подмосковье нашли похороненную заживо овчарку']

## Рубрикация

In [ ]:
target_labels = set(train_dataset["topic"].dropna().tolist())
target_labels -= {"69-я параллель", "Крым", "Культпросвет ", "Оружие", "Бизнес", "Путешествия"}
target_labels = list(target_labels)
print(target_labels)

['Наука и техника', 'Спорт', 'Интернет и СМИ', 'Бывший СССР', 'Экономика', 'Силовые структуры', 'Из жизни', 'Культура', 'Россия', 'Ценности', 'Дом', 'Мир']


In [ ]:
pattern = r'(\b{}\b)'.format('|'.join(target_labels))

train_with_topics = train_dataset[train_dataset["topic"].str.contains(pattern, case=False, na=False)]
train_with_topics = train_with_topics.head(20000)

test_with_topics = test_dataset[test_dataset["topic"].str.contains(pattern, case=False, na=False)]

<ipython-input-28-578f28dae61e>:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  train_with_topics = train_dataset[train_dataset["topic"].str.contains(pattern, case=False, na=False)]
<ipython-input-28-578f28dae61e>:6: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  test_with_topics = test_dataset[test_dataset["topic"].str.contains(pattern, case=False, na=False)]


In [ ]:
import numpy as np

y_train = train_with_topics["topic"].apply(lambda x: target_labels.index(x)).to_numpy()
X_train = np.zeros((train_with_topics.shape[0], model.vector_size))
for i, embedding in enumerate(train_with_topics["text"]):
    X_train[i, :] = get_text_embedding(model, embedding)

y_test = test_with_topics["topic"].apply(lambda x: target_labels.index(x)).to_numpy()
X_test = np.zeros((test_with_topics.shape[0], model.vector_size))
for i, embedding in enumerate(test_with_topics["text"]):
    X_test[i, :] = get_text_embedding(model, embedding)

print(X_train.shape)
print(y_train)

(20000, 32)
[11 11  7 ...  2  4  9]


In [ ]:
from sklearn.svm import SVC

clf = SVC()
clf.fit(X_train, y_train)

SVC()

In [ ]:
from sklearn import metrics

y_predicted = clf.predict(X_test)
print(metrics.classification_report(y_test, y_predicted))

              precision    recall  f1-score   support

           0       0.78      0.78      0.78      2119
           1       0.90      0.88      0.89      3429
           2       0.61      0.54      0.57      2447
           3       0.71      0.49      0.58      2156
           4       0.68      0.78      0.73      3185
           5       0.67      0.62      0.64      1663
           6       0.70      0.71      0.70      2191
           7       0.71      0.63      0.66      1995
           8       0.55      0.64      0.59      4324
           9       0.81      0.63      0.71      1177
          10       0.74      0.54      0.63      1182
          11       0.66      0.77      0.71      4291

    accuracy                           0.69     30159
   macro avg       0.71      0.67      0.68     30159
weighted avg       0.70      0.69      0.69     30159



### Задание: Больше точности

Увеличить точность на 0.02+ на той же Word2Vec модели (например, используя tf-idf при построении вектора текста)

In [ ]:
from collections import Counter
import itertools
import numpy as np

def get_text_embedding_tfidf(model, phrase, doc_cnt, N_doc):

    embeddings = np.array([model.get_vector(word.text.lower()) 
                           if word.text.lower() in model.vocab else np.zeros((model.vector_size,))
                           for word in tokenize(phrase)])

    phrase_tok = [j.text.lower() for j in tokenize(phrase)]
    phrase_cnt = Counter(phrase_tok)

    tf = [phrase_cnt[i] for i in phrase_tok]
    df = [doc_cnt[i] for i in phrase_tok]
    w = np.array([x*np.log(N_doc/y) for x,y in zip(tf, df)])

    return embeddings.T.dot(w)

text_tok = [ [j.text.lower() for j in tokenize(i)] for i in test_titles ] #список токенизированных предложений
text_tok = [list(set(i)) for i in text_tok] #убираем дубли слов в каждом предложении
text_tok = list(itertools.chain(*text_tok)) #list of list -> list
doc_cnt = Counter(text_tok)                 #подсчет в скольки доках встречается каждое слово корпуса
N_doc = len(test_titles)                    #кол-во доков
get_text_embedding_tfidf(model, "В Москве нашли", doc_cnt, N_doc)

array([  4.81330877, -11.88436551, -10.22798918,   3.49487539,
        -5.1980293 ,  19.23108045, -21.36190056, -17.47380334,
         1.88609873,  27.64861281,  18.25445472, -22.0517959 ,
        -2.56994361,  24.20933447,  12.09612488,   6.64264077,
        -8.1882366 ,  17.32547196,  13.13231317,  -6.91449006,
        -4.08539902,   3.99387133,  -4.78182338,  -0.36248205,
        19.98499575,  16.88553298, -24.17800151,  -2.99653241,
       -22.13430599, -25.53571393,  12.66146446,   2.84107181])

In [ ]:
y_train = train_with_topics["topic"].apply(lambda x: target_labels.index(x)).to_numpy()
X_train = np.zeros((train_with_topics.shape[0], model.vector_size))

train_text_tok = [ [j.text.lower() for j in tokenize(i)] for i in train_with_topics["text"] ]
train_text_tok = [list(set(i)) for i in train_text_tok]
train_text_tok = list(itertools.chain(*train_text_tok))
train_doc_cnt = Counter(train_text_tok)
train_N_doc = len(train_with_topics["text"])
for i, embedding in enumerate(tqdm(train_with_topics["text"])):
    X_train[i, :] = get_text_embedding_tfidf(model, embedding, train_doc_cnt, train_N_doc)

y_test = test_with_topics["topic"].apply(lambda x: target_labels.index(x)).to_numpy()
X_test = np.zeros((test_with_topics.shape[0], model.vector_size))
test_text_tok = [ [j.text.lower() for j in tokenize(i)] for i in test_with_topics["text"] ]
test_text_tok = [list(set(i)) for i in test_text_tok]
test_text_tok = list(itertools.chain(*test_text_tok))
test_doc_cnt = Counter(test_text_tok)
test_N_doc = len(test_with_topics["text"])
for i, embedding in enumerate(tqdm(test_with_topics["text"])):
    X_test[i, :] = get_text_embedding_tfidf(model, embedding, test_doc_cnt, test_N_doc)

print(X_train.shape)
print(y_train)

100%|██████████| 30159/30159 [04:21<00:00, 115.21it/s]

(20000, 32)
[11 11  7 ...  2  4  9]


In [ ]:
from sklearn.svm import SVC
from sklearn import metrics

clf = SVC()
clf.fit(X_train, y_train)

y_predicted = clf.predict(X_test)
print(metrics.classification_report(y_test, y_predicted))

              precision    recall  f1-score   support

           0       0.78      0.77      0.78      2119
           1       0.90      0.89      0.90      3429
           2       0.63      0.58      0.60      2447
           3       0.74      0.52      0.61      2156
           4       0.67      0.79      0.72      3185
           5       0.66      0.61      0.63      1663
           6       0.71      0.68      0.70      2191
           7       0.72      0.68      0.70      1995
           8       0.57      0.62      0.59      4324
           9       0.85      0.67      0.75      1177
          10       0.66      0.55      0.60      1182
          11       0.66      0.77      0.71      4291

    accuracy                           0.70     30159
   macro avg       0.71      0.68      0.69     30159
weighted avg       0.70      0.70      0.70     30159



## Предобученные векторы

### Задание: Модели rusvectores
Используя fastText модели с rusvectores, достигните хотя бы такой же точности рубрикации

In [ ]:
# https://rusvectores.org/ru/models/
!wget http://vectors.nlpl.eu/repository/20/187.zip
!unzip 187.zip -d rusvetores_187

Archive:  187.zip
  inflating: rusvetores_187/meta.json  
  inflating: rusvetores_187/model.model  
  inflating: rusvetores_187/model.model.vectors_ngrams.npy  
  inflating: rusvetores_187/model.model.vectors.npy  
  inflating: rusvetores_187/model.model.vectors_vocab.npy  
  inflating: rusvetores_187/README   


In [ ]:
from gensim.models import KeyedVectors
fasttext_model = KeyedVectors.load("rusvetores_187/model.model")

In [ ]:
import numpy as np

y_train = train_with_topics["topic"].apply(lambda x: target_labels.index(x)).to_numpy()
X_train = np.zeros((train_with_topics.shape[0], fasttext_model.vector_size))
for i, embedding in enumerate(train_with_topics["text"]):
    X_train[i, :] = get_text_embedding(fasttext_model, embedding)

y_test = test_with_topics["topic"].apply(lambda x: target_labels.index(x)).to_numpy()
X_test = np.zeros((test_with_topics.shape[0], fasttext_model.vector_size))
for i, embedding in enumerate(test_with_topics["text"]):
    X_test[i, :] = get_text_embedding(fasttext_model, embedding)

print(X_train.shape)
print(y_train)

(20000, 300)
[11 11  7 ...  2  4  9]


In [ ]:
from sklearn.svm import SVC
from sklearn import metrics

clf = SVC()
clf.fit(X_train, y_train)

y_predicted = clf.predict(X_test)
print(metrics.classification_report(y_test, y_predicted))

              precision    recall  f1-score   support

           0       0.81      0.83      0.82      2119
           1       0.93      0.89      0.91      3429
           2       0.65      0.59      0.62      2447
           3       0.79      0.62      0.70      2156
           4       0.73      0.78      0.75      3185
           5       0.70      0.65      0.67      1663
           6       0.77      0.72      0.74      2191
           7       0.84      0.73      0.78      1995
           8       0.64      0.73      0.68      4324
           9       0.83      0.70      0.76      1177
          10       0.75      0.71      0.73      1182
          11       0.71      0.83      0.76      4291

    accuracy                           0.75     30159
   macro avg       0.76      0.73      0.74     30159
weighted avg       0.75      0.75      0.75     30159

